[#39] Addresses suggestions re iRODS file system setup UX.
rspace-os/rspace-web pull request #44
Opened 2024-07-02 13:54 UTC by ll4strw

Retrieve and use default labels from system.properties.

2024-07-04 10:26 UTC, rs-nicof requested changes
Can you possibly rebase your PR? 🙏 
it looks like there are commits that are not part of it so it is difficult to understand what to review

2024-07-05 12:30 UTC, ll4strw commented
@rs-nicof rebase done.

2024-08-15 15:02 UTC, mKowalski256 commented
Let me merge this PR so we have all suggested fixes inside [rspace-os:irods](https://github.com/rspace-os/rspace-web/tree/irods) branch, and then the main #40 to discuss is one merging into [rspace-os:main](https://github.com/rspace-os/rspace-web/tree/main) branch.

2024-08-15 15:04 UTC, mKowalski256 commented
I have read the CLA Document and I hereby sign the CLA

2024-08-15 15:06 UTC, merged